version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- ps: nuget restore "src/Sanderling/Sanderling.sln"
build:
  project: src/Sanderling/Sanderling.sln
  verbosity: normal
artifacts:
- path: src\Sanderling\Sanderling.Exe\bin\Debug\Sanderling.Exe.exe
  name: Sanderling.exe